
name: Shedule

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          gh workflow run reuse.yml -f foo=randomBlah
