name: Shedule

on:
  workflow_dispatch:

  schedule:
    - cron: '*/15 * * * *'

# permissions:
#  actions: write
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run scheduled jobs
      env:
        eventp: "ss"
      run: |
        set -x
        echo "${{ toJson(github) }}"

