
name: Shedule

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  reusable_workflow_job:
    uses: zaelar/workflows/.github/workflows/reuse.yml@main
    with:
        foo: "bar"
