
name: CI

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: zaelar/workflows/.github/workflows/reuse.yml@main
      with:
        foo: "bar"
