name: Shedule

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * 0-5 2-6'
# permissions:
#  actions: write
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run scheduled jobs
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x
        echo "${{ github.event }}"
        currentHour=$(date "+%H")
        dayOfWeek=$(date "+%w")
        if [ -d "schedules/all/${currentHour}" ] ; then
          echo "Running jobs in ${jobDir}"
          for job in $(ls -1 schedules/all/${currentHour}/*.json ); do
            echo "Executing schedule with ${job}"
            cat "${job}" | gh workflow run .github/workflows/reuse.yml --json 
          done
        fi
        if [ -d "schedules/${dayOfWeek}/${currentHour}" ] ; then
          echo "Running jobs in ${jobDir}"
          for job in $(ls -1 schedules/${dayOfWeek}/${currentHour}/*.json ); do
            echo "Executing schedule with ${job}"
            cat "${job}" | gh workflow run .github/workflows/reuse.yml --json 
          done
        fi
